# Generated by Django 5.1.1 on 2024-10-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='date_added',
            field=models.DateTimeField(null=True),
        ),
    ]
