# Generated by Django 5.1.1 on 2024-10-11 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_brinquedo'),
    ]

    operations = [
        migrations.CreateModel(
            name='material_de_um_brinquedo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=20)),
                ('quantidade', models.IntegerField()),
                ('brinquedo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Brinquedo', to='estoque.brinquedo')),
            ],
        ),
    ]
