# Generated by Django 5.1.1 on 2024-10-14 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_material_de_um_brinquedo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material_de_um_brinquedo',
            name='brinquedo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Brinquedo', to='estoque.brinquedo'),
        ),
    ]
